version: "3.8"

services:
  server: 
    platform: linux/arm64/v8
    image: "nginx:stable-alpine"
    ports:
      - '8000:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  php: 
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    # ports: #we don't need to expose any ports on localhost because the php container is talking
    # directly to the nginx container. 
    #   - '3000:9000' # syntax host-machine:internal
  mysql:
    platform: linux/x86_64
    image: "mysql:5.7"
    env_file:
      - ./env/mysql.env
  composer: 
    build: 
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html

  # artisan:
  # npm: 
